services:
    application:
        container_name: bundle_toolbox_app
        image: richcongress/php:8.1
        volumes:
            - .:/app
            - ~/.composer:/home/application/.composer:cached

